[package]
name = "pyrefly-producer"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
pyrefly = { git = "https://github.com/facebook/pyrefly.git", rev = "1d64c4b605445f43d66162e56592837223b3dabf" }
pyrefly_util = { git = "https://github.com/facebook/pyrefly.git", rev = "1d64c4b605445f43d66162e56592837223b3dabf" }
ruff_python_ast = "0.0.10"
ruff_text_size = "0.0.10"
protobuf = { workspace = true }
scip = { workspace = true }
code-reality = { path = "../code-reality" }

[dev-dependencies]
rusqlite = { workspace = true }
